### ISSUE TITLE
服务器运行报错怎么办…

### ISSUE THREAD

**Issue by huanruomengyun** [iyear/E5SubBot#8]
输入 ./E5SubBot
报错如下
```
[root@Linux]# ./E5SubBot
2020/06/07 15:20:54 While parsing config: yaml: line 22: mapping values are not allowed in this context
ERROR
panic: While parsing config: yaml: line 22: mapping values are not allowed in this context

goroutine 1 [running]:                                                           
main.CheckErr(0xa3efa0, 0xc00010c760, 0xc00010c760)
        E:/GoProjects/E5SubBot/main/util.go:26 +0x101
main.init.0()
        E:/GoProjects/E5SubBot/main/handle.go:54 +0xb5
```
配置文件如下：
```
#bindmax,notice,admin,errlimit可热更新，直接更新config.yml保存即可
##更换为自己的BotToken

bot_token: 10219xxxx1:AAGfUFn3SnERpxFTzAxxxxxxx

##不需要socks5代理删去即可
socks5: 127.0.0.1:1080

##公告，合并至/help
notice: "第一行\n第二行"
##管理员tgid，前往https://t.me/userinfobot获取，用,隔开
##管理员权限: 手动调用任务，获得任务总反馈
admin: 991535xxx1
##任务最大出错次数，满后自动解绑账户并发送通知，无限次数将值改为负数(-1)即可 
##以ms账户为单位，不会解绑所有账户(只解绑错误账户) 
##主要为了减少资源浪费.bot重启后会清零所有错误次数 
errlimit: 5
##API调用频率，使用cron表达式
cron: "1 */3 * * *"
##最大可绑定数
bindmax: 3                                                                       ##mysql配置，请提前创建数据库
mysql:                                                                            
          host: 127.0.0.1                                                                    
          port: 3306                                                                         
          user: e5sub
          password: e5sub                                                                  
          database: e5sub
```

**Comment by iyear** [comment]
yaml格式错误，估计mysql这里的缩进问题
